#ifndef BIT_MATH_H_INCLUDED
#define BIT_MATH_H_INCLUDED

#define SET_BIT(REG,BIT_NUM)        REG|=(1<<BIT_NUM)
#define CLEAR_BIT(REG,BIT_NUM)      REG&=~(1<<BIT_NUM)
#define TOOGLE_BIT(REG,BIT_NUM)     REG^=(1<<BIT_NUM)
#define CHK_BIT(REG,BIT_NUM)      ((REG>>BIT_NUM)&1)


#endif // BIT_MATH_H_INCLUDED
